### ISSUE TITLE
error when running createInstance.py

### ISSUE THREAD

**Issue by carlost** [trevor-laher/OnDemandMinecraft#12]
I am going to be honest, I don't think that I have spun up an ec2 instance on my personal AWS account since they started pushing ec2 instances into VPCs by default.  So this is most likely a **me** issue.

When i run the createInstance.py script i end up running into an error from boto3:

```
$ python utilityScripts/createInstance.py
Traceback (most recent call last):
  File "utilityScripts/createInstance.py", line 21, in <module>
    SecurityGroups = Config.ec2_secgroups)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (VPCResourceNotSpecified) when calling the RunInstances operation: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
```

Config is as follows:

```python
class Config:
    #AWS Information
    ACCESS_KEY = 'XXXXXXXX'
    SECRET_KEY = 'SOMEMOREXXXXs'
    INSTANCE_ID = ''
    ec2_region = "us-east-1"
    ec2_amis = ['ami-0b2f2d7c5173e3a44']
    ec2_keypair = 'minecraft'
    ec2_secgroups = ['minecraft']
    ec2_instancetype = 't3.small'

    #SSH Key Path
    SSH_KEY_FILE_PATH = './minecraft_ec2.pem'

    #Server Memory Size
    #This is default to no memory specification but can be: '-Xmx1024M -Xms1024M ' (KEEP TRAILING SPACE)
    MEMORY_ALLOCATION=''

    # heroku server password
    SERVER_PASSWORD='SUPERSECRET'
```

I tried a new different models from other ec2 instance types with the same results which led me to ec2-classic vs VPC as being the likely culprit.  When i tried to spin up an ec2 instance in the AWS console I couldn't select ec2-classic, even though my account had the relevant account attributes:

<img width="386" alt="Screen Shot 2019-07-04 at 12 53 57 PM" src="https://user-images.githubusercontent.com/514078/60681149-249d9e00-9e5c-11e9-9b8d-e73745d1e806.png">

I am going to dig into the aws ec2-classic vs VPC and bota3 docs later when my kids aren't begging me to play minecraft with them :)  I will update this issue with anything i turn up: default VPC/subnet settings, ec2-classic config etc. 

In the mean time if anyone has already run through this ... please let me know :)

**Comment by trevor-laher** [comment]
Not sure how old your account is but there appears to be a default VPC change that took place for accounts created after 2013-12-04. This link might have your answer: https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-in-vpc.html

**Comment by trevor-laher** [comment]
Also not sure if this project is running on EC2 Classic. There does appear to be a VPC parameter you can configure in server.py for instance creation. Check out the EC2.client docs in boto3.
