### ISSUE TITLE
gunicorn worker failed to boot

### ISSUE THREAD

**Issue by DylanDelobel** [trevor-laher/OnDemandMinecraft#7]
Here the traceback

```
2019-06-30T19:27:21.564341+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-06-30T19:27:21.564342+00:00 app[web.1]:
2019-06-30T19:27:21.564345+00:00 app[web.1]: Traceback (most recent call last):
2019-06-30T19:27:21.564352+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2019-06-30T19:27:21.564449+00:00 app[web.1]: sys.exit(run())
2019-06-30T19:27:21.564452+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
2019-06-30T19:27:21.564632+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2019-06-30T19:27:21.564636+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
2019-06-30T19:27:21.564786+00:00 app[web.1]: super(Application, self).run()
2019-06-30T19:27:21.564790+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
2019-06-30T19:27:21.564918+00:00 app[web.1]: Arbiter(self).run()
2019-06-30T19:27:21.564925+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
2019-06-30T19:27:21.565110+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2019-06-30T19:27:21.565113+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
2019-06-30T19:27:21.565293+00:00 app[web.1]: self.stop()
2019-06-30T19:27:21.565297+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
2019-06-30T19:27:21.565540+00:00 app[web.1]: time.sleep(0.1)
2019-06-30T19:27:21.565547+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
2019-06-30T19:27:21.565816+00:00 app[web.1]: self.reap_workers()
2019-06-30T19:27:21.565823+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2019-06-30T19:27:21.566277+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2019-06-30T19:27:21.566292+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2019-06-30T19:27:21.685142+00:00 heroku[web.1]: State changed from up to crashed
2019-06-30T19:27:21.664448+00:00 heroku[web.1]: Process exited with status 1
```

I solved this by changing the gunicorn version to `0.18` in requirements

**Comment by Gezili** [comment]
Hello, I get the exact issue. However, there does not appear to be a 0.18 version of gunicorn. Which version did you actually use?

**Comment by jreneew2** [comment]
That could be any error. What you can do is add --preload to your Procfile and it will show more specific error. I added that to mine and it ended up being a Path error. Turns out I forgot to commit my key-perms file which caused it to crash. Probably should add more specific error messages.

**Comment by shakura** [comment]
I've got exact the same exception. Pem file was in gitignore, so I've deleted gitignore rule, pushed the pem file and it worked

**Comment by mezitax** [comment]
there should be a warning in readme.md
.gitignore by default adds exception of * .pem

**Comment by getsec** [comment]
@shakura  please mark this as closed if that fixed it :D

**Comment by shakura** [comment]
@getsec I think we can mark it as closed only when gitignore is fixed :P (or README.md)
